donate_2023:
  id: donate_2023
  alt: OpenStreetMap Funding Drive 2023
  link: https://supporting.openstreetmap.org/
  img: banners/donate_2023_1.jpg
  srcset:
    - [banners/donate_2023_1.jpg, 1x]
    - [banners/donate_2023_1@2x.jpg, 2x]
  dark: true
  enddate: 2023-dec-31
sotmeu_2024:
  id: sotmeu_2024
  alt: State of the Map Europe 2024
  link: https://openstreetmap.org.pl/2024/sotm-eu-2024-community-tickets-70/
  img: banners/StateoftheMapEurope_2024.png
  enddate: 2024-jul-18
sotm_2024:
  id: sotm_2024
  alt: State of the Map 2024
  link: https://2024.stateofthemap.org
  img: banners/sotm_2024.png
  srcset:
    - [banners/sotm_2024.png, 1x]
    - [banners/sotm_2024@2x.png, 2x]
  startdate: 2024-jul-10
  enddate: 2024-sep-05